@Techan.Presentation_HostAddress = http://localhost:44237

GET https://localhost:44327/Brands
Accept: application/json

###


POST https://localhost:44327/Brands
Accept:application/json
Body:{
  BrandDetails:[{Name:"Az",Desription:"AZ",LanguageId:1}]
}